### PR TITLE
recipe data page

### PR DESCRIPTION
**Pull request by hudsonschmidt**
Added a page to display recipe data when clicking on item from browse

### CODE REVIEW

**Comment by dragon123al** [comment]
looks good

**Comment by apervmm** [comment]
Looks solid, but it needs a little more work since routes should be different for each item recipe. Hence, it's better to write another routing the first fetches from the backend an API GET: meals/<id>, then dynamically pass it to routes.

**Comment by NingusKhan** [comment]
Great work, I will get started branching this and finishing recipe loading on the page this afternoon. Let me know if there's any styling I should watch out for.

You're a beast
Max

**Comment by kyyyyle** [comment]
Looked through the changes. Looks good to me.

**Pull request merged**
